### ISSUE TITLE
KeyError: 'sort'

### ISSUE THREAD

**Issue by sanicki** [hjalp/leddit#1]
Thanks for releasing this. I'm trying to set it up for a very small subreddit with 4.4k subscribers until Lemmy adoption will support that kind of niche community.

When I try to run it I am getting the following "KeyError":

```
Traceback (most recent call last):
  File "/home/ubuntu/leddit/src/main.py", line 74, in <module>
    syncer.scrape_new_posts()
  File "/home/ubuntu/leddit/src/utils/syncer.py", line 32, in scrape_new_posts
    sort = com['sort']
           ~~~^^^^^^^^
KeyError: 'sort'
```

**Comment by hjalp** [comment]
Hey, thanks for trying out the bot! What does the `community_map` part of your `config.yaml` file look like? I realize that the tooltip saying that "`sort` defaults to new if not provided" might imply that it can be removed entirely from the `community_map`, although what it actually means is that `sort` can be left blank. The code will look for it and crash if it's not there at all.

I think it also defaults to `hot` rather than `new` right now. I'll add a check for missing items in the config that will print clear error messages instead of this.

This is what the `community_map` should look like:
```yaml
community_map:
  - subreddit: subreddit_name
    community: lemmy_community
    sort: new
    post_header: '##### This is an automated archive made by the [Leddit Bot](https://github.com/hjalp/leddit).'
```
